//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Packages/com.fakecorps.vnovelizer/Runtime/Resources/VNInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VNInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VNInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VNInputActions"",
    ""maps"": [
        {
            ""name"": ""VNControls"",
            ""id"": ""7a79abe4-224b-434f-b972-671d6fd42609"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""a22b3719-886b-4fc1-8d48-d151e7ae9fcd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""e9b778a9-71ce-4e73-8bd4-1236ae80a8c1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Log"",
                    ""type"": ""Button"",
                    ""id"": ""8ecb0a56-c935-4d95-a57f-46ef0f39f29a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hide"",
                    ""type"": ""Button"",
                    ""id"": ""d5e19c50-ceed-4d34-8022-6dd3e01eca57"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Auto"",
                    ""type"": ""Button"",
                    ""id"": ""6a516326-28ab-4c89-830f-6ed2aa685aca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""b8c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings"",
                    ""type"": ""Button"",
                    ""id"": ""b4dc3bdd-de00-4962-836b-6d84fbbe374f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""87be3bd8-ea6d-4742-b97f-32c2e69a865a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1b0fb45-7ed3-447c-9f35-b13e860c2f82"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1fc5812-8e56-4bcd-ab04-f0aa68051ca2"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8cf41c-d0c3-4ffc-ab54-2ff28f83a39d"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a16bb8c7-9d61-4896-9ba9-0b7a394dcc28"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Log"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""077033ab-77ab-4422-bbbf-35e7999157d8"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Log"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""188cf526-c9eb-4243-9e9d-7ae2d3e0cf2d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""829b12d4-1f26-4f5b-bb4d-a22e69158cb8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1d5ebb8-8c4b-4fee-9637-c4744cfc5cee"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""27a5ad5d-f106-41c4-a97b-f264087a9249"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""95223eda-6010-48b7-bf05-eb7e8fd69d66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8d87a3b5-69e6-4623-b87f-508ba9d4772d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""VNControls"",
            ""bindingGroup"": ""VNControls"",
            ""devices"": []
        }
    ]
}");
        // VNControls
        m_VNControls = asset.FindActionMap("VNControls", throwIfNotFound: true);
        m_VNControls_Confirm = m_VNControls.FindAction("Confirm", throwIfNotFound: true);
        m_VNControls_Skip = m_VNControls.FindAction("Skip", throwIfNotFound: true);
        m_VNControls_Log = m_VNControls.FindAction("Log", throwIfNotFound: true);
        m_VNControls_Hide = m_VNControls.FindAction("Hide", throwIfNotFound: true);
        m_VNControls_Auto = m_VNControls.FindAction("Auto", throwIfNotFound: true);
        m_VNControls_Save = m_VNControls.FindAction("Save", throwIfNotFound: true);
        m_VNControls_Settings = m_VNControls.FindAction("Settings", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Newaction = m_UI.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VNControls
    private readonly InputActionMap m_VNControls;
    private List<IVNControlsActions> m_VNControlsActionsCallbackInterfaces = new List<IVNControlsActions>();
    private readonly InputAction m_VNControls_Confirm;
    private readonly InputAction m_VNControls_Skip;
    private readonly InputAction m_VNControls_Log;
    private readonly InputAction m_VNControls_Hide;
    private readonly InputAction m_VNControls_Auto;
    private readonly InputAction m_VNControls_Save;
    private readonly InputAction m_VNControls_Settings;
    public struct VNControlsActions
    {
        private @VNInputActions m_Wrapper;
        public VNControlsActions(@VNInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_VNControls_Confirm;
        public InputAction @Skip => m_Wrapper.m_VNControls_Skip;
        public InputAction @Log => m_Wrapper.m_VNControls_Log;
        public InputAction @Hide => m_Wrapper.m_VNControls_Hide;
        public InputAction @Auto => m_Wrapper.m_VNControls_Auto;
        public InputAction @Save => m_Wrapper.m_VNControls_Save;
        public InputAction @Settings => m_Wrapper.m_VNControls_Settings;
        public InputActionMap Get() { return m_Wrapper.m_VNControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VNControlsActions set) { return set.Get(); }
        public void AddCallbacks(IVNControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_VNControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VNControlsActionsCallbackInterfaces.Add(instance);
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Skip.started += instance.OnSkip;
            @Skip.performed += instance.OnSkip;
            @Skip.canceled += instance.OnSkip;
            @Log.started += instance.OnLog;
            @Log.performed += instance.OnLog;
            @Log.canceled += instance.OnLog;
            @Hide.started += instance.OnHide;
            @Hide.performed += instance.OnHide;
            @Hide.canceled += instance.OnHide;
            @Auto.started += instance.OnAuto;
            @Auto.performed += instance.OnAuto;
            @Auto.canceled += instance.OnAuto;
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
            @Settings.started += instance.OnSettings;
            @Settings.performed += instance.OnSettings;
            @Settings.canceled += instance.OnSettings;
        }

        private void UnregisterCallbacks(IVNControlsActions instance)
        {
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Skip.started -= instance.OnSkip;
            @Skip.performed -= instance.OnSkip;
            @Skip.canceled -= instance.OnSkip;
            @Log.started -= instance.OnLog;
            @Log.performed -= instance.OnLog;
            @Log.canceled -= instance.OnLog;
            @Hide.started -= instance.OnHide;
            @Hide.performed -= instance.OnHide;
            @Hide.canceled -= instance.OnHide;
            @Auto.started -= instance.OnAuto;
            @Auto.performed -= instance.OnAuto;
            @Auto.canceled -= instance.OnAuto;
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
            @Settings.started -= instance.OnSettings;
            @Settings.performed -= instance.OnSettings;
            @Settings.canceled -= instance.OnSettings;
        }

        public void RemoveCallbacks(IVNControlsActions instance)
        {
            if (m_Wrapper.m_VNControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVNControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_VNControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VNControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VNControlsActions @VNControls => new VNControlsActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Newaction;
    public struct UIActions
    {
        private @VNInputActions m_Wrapper;
        public UIActions(@VNInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_UI_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_VNControlsSchemeIndex = -1;
    public InputControlScheme VNControlsScheme
    {
        get
        {
            if (m_VNControlsSchemeIndex == -1) m_VNControlsSchemeIndex = asset.FindControlSchemeIndex("VNControls");
            return asset.controlSchemes[m_VNControlsSchemeIndex];
        }
    }
    public interface IVNControlsActions
    {
        void OnConfirm(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
        void OnLog(InputAction.CallbackContext context);
        void OnHide(InputAction.CallbackContext context);
        void OnAuto(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnSettings(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
